# Generated by Django 3.1.5 on 2021-01-31 22:42

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='E-Mail')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/image')),
                ('cell', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Esta activo?')),
                ('is_staff', models.BooleanField(blank=True, default=True, verbose_name='Es del Equipo?')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registo')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('groups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ('date_joined',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(help_text='Unique value for product page URL, created from name.', unique=True)),
                ('image', models.CharField(blank=True, max_length=350, null=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('meta_keywords', models.CharField(help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255, verbose_name='Meta Keywords')),
                ('meta_description', models.CharField(help_text='Content for description meta tag', max_length=255, verbose_name='Meta Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CategoryMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(help_text='Unique value for product page URL, created from name.', unique=True)),
                ('image', models.CharField(blank=True, max_length=350, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'CategoriesMain',
                'db_table': 'categoriesmain',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Deliveryman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='Unique value for repartidor page URL, created from nombre.', max_length=255, unique=True)),
                ('cell', models.CharField(blank=True, max_length=15, null=True)),
                ('is_activo', models.BooleanField(default=True)),
                ('quantityday', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'deliveryman',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateorder', models.DateField()),
                ('state', models.CharField(default='pendiente', max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery', models.BooleanField(default=False)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('order_lat', models.DecimalField(decimal_places=7, default=-12.54299, max_digits=15)),
                ('order_lon', models.DecimalField(decimal_places=7, default=-74.60863, max_digits=15)),
                ('datedelivery', models.DateField()),
                ('deliveryman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdeliveryman', to='core.deliveryman')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='Unique value for Locales page URL, created from nombre.', max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('shop_lat', models.DecimalField(decimal_places=7, default=-12.54299, max_digits=15)),
                ('shop_lon', models.DecimalField(decimal_places=7, default=-74.60863, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('hour_sem', models.CharField(blank=True, max_length=50, null=True)),
                ('hour_fsem', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Stores',
                'db_table': 'stores',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Zonapais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(blank=True, max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('distrito', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Zonapais',
                'db_table': 'zonapais',
                'ordering': ['departamento', 'provincia', 'distrito'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Unique value for product page URL, created from name.', max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True)),
                ('talla', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.CharField(blank=True, max_length=350, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recomendations', models.IntegerField(default=0)),
                ('offer', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='Content for description meta tag', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='core.category')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productstore', to='core.store')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photosproduct', to='core.product')),
            ],
            options={
                'verbose_name_plural': 'Photos',
                'db_table': 'photos',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='usuarios/fotos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('image_product', models.CharField(blank=True, max_length=255, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderdetail', to='core.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderdetailproduct', to='core.product')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderdetailstore', to='core.store')),
            ],
            options={
                'db_table': 'order_detail',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='zonapais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderzonapais', to='core.zonapais'),
        ),
        migrations.AddField(
            model_name='category',
            name='categoriesmain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='core.categorymain'),
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='Unique value for Almacen page URL, created from nombre.', max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('almacen_lat', models.DecimalField(decimal_places=7, default=-12.54299, max_digits=15)),
                ('almacen_lon', models.DecimalField(decimal_places=7, default=-74.60863, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almacenstore', to='core.store')),
            ],
            options={
                'verbose_name_plural': 'Almacenes',
                'db_table': 'almacenes',
            },
        ),
    ]
