# Generated by Django 3.1.5 on 2021-01-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zonapais',
            options={'ordering': ['departamento', 'provincia', 'distrito'], 'verbose_name_plural': 'Zonapais'},
        ),
        migrations.AddField(
            model_name='order_detail',
            name='image_product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='zonapais',
            table='zonapais',
        ),
    ]
